#
## Makefile for the touchscreen drivers.
#
#
## Each configuration option enables a list of files.

# Touch Core Driver Common Header Code..!!
ccflags-y += -I$(srctree)/drivers/input/touchscreen/lge/

obj-$(CONFIG_LGE_TOUCH_DLKM_LGSIC_SW82906)           += sw82906/
obj-$(CONFIG_LGE_TOUCH_DLKM_LGSIC_SW82908)           += sw82908/
