#
## Makefile for the module touchscreen drivers.
#

# Touch Core Driver Common Header Code..!!
#ccflags-y += -I$(srctree)/drivers/input/touchscreen/lge/

obj-$(CONFIG_LGE_TOUCH_DLKM_LGSIC_SW82908)      += touch_module_sw82908.o
touch_module_sw82908-objs					+= touch_sw82908.o
touch_module_sw82908-objs					+= touch_sw82908_prd.o
