obj-$(CONFIG_APPLICATION_MANAGER) +=	application_manager_module.o \
					application_manager.o \
					application_cluster_pattern.o \
					ordered_application_cluster_pattern.o \
					prelaunch_application_cluster_pattern.o \
					application_prelaunch.o \
					pattern_manager.o
